on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, macos]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run mandatory tests
        run: |
          echo "Running mandatory tests..."
